import "./globals.css";
import type { Metadata } from "next";

import { Montserrat, Manrope } from 'next/font/google';
import { Header } from "./header/Header";

const montserrat = Montserrat({
  subsets: ['cyrillic'],  
  variable: '--font-montserrat',
});

const manrope = Manrope({
  subsets: ['cyrillic'],
  variable: '--font-manrope',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${manrope.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
